const data =
   [
       {x:0, y:0, flag:false},
       {x:0, y:1, flag:true},
       {x:0, y:2,flag:true},
       {x:0, y:3,flag:true},
       {x:0, y:4,flag:true},
       {x:0, y:5,flag:true},
       {x:0, y:6,flag:true},
       {x:0, y:7,flag:true},
       {x:0, y:8,flag:true},
       {x:0, y:9,flag:true},
       {x:1, y:0,flag:true},
       {x:1, y:1,flag:true},
       {x:1, y:2,flag:true},
       {x:1, y:3,flag:true},
       {x:1, y:4,flag:true},
       {x:1, y:5,flag:true},
       {x:1, y:6,flag:true},
       {x:1, y:7,flag:true},
       {x:1, y:8,flag:true},
       {x:1, y:9,flag:true},
       {x:2, y:0,flag:true},
       {x:2, y:1,flag:true},
       {x:2, y:2,flag:true},
       {x:2, y:3,flag:true},
       {x:2, y:4,flag:true},
       {x:2, y:5,flag:true},
       {x:2, y:6,flag:true},
       {x:2, y:7,flag:true},
       {x:2, y:8,flag:true},
       {x:2, y:9,flag:true},
       {x:3, y:0,flag:true},
       {x:3, y:1,flag:true},
       {x:3, y:2,flag:true},
       {x:3, y:3,flag:true},
       {x:3, y:4,flag:true},
       {x:3, y:5,flag:true},
       {x:3, y:6,flag:true},
       {x:3, y:7,flag:true},
       {x:3, y:8,flag:true},
       {x:3, y:9,flag:true},
       {x:4, y:0,flag:true},
       {x:4, y:1,flag:true},
       {x:4, y:2,flag:true},
       {x:4, y:3,flag:true},
       {x:4, y:4,flag:true},
       {x:4, y:5,flag:true},
       {x:4, y:6,flag:true},
       {x:4, y:7,flag:true},
       {x:4, y:8,flag:true},
       {x:4, y:9,flag:true}
   ]
    export default data;
